### ISSUE TITLE
return HTTP Status 400 – Bad Request for any request

### ISSUE THREAD

**Issue by kyoneo** [SAP-samples/cloud-objectstore-java-sample#12]
HI Team,

I am working on a tutorial on using Object Store, but any type of request to the deployed application returns HTTP Status 400 - Bad Request.
Here is my modified manifest.yaml:

```
---
applications:
- name: objectstore-sample-svc_4585
  random-route: true
  memory: 2G
  buildpack: https://github.com/cloudfoundry/java-buildpack.git
  path: target/objectstore-sample-1.0.0.jar
  services:
    - objectstore-service

```
Here is my application after deployment (cf a)

```
name:              objectstore-sample-svc_4585
requested state:   started
routes:           *******.com
last uploaded:     Tue 16 Nov 16:04:23 JST 2021
stack:             cflinuxfs3
buildpacks:        
        name                                                 version                                                              detect output   buildpack name
        https://github.com/cloudfoundry/java-buildpack.git   11e457b-https://github.com/cloudfoundry/java-buildpack.git#11e457b   java            java

type:           web
sidecars:       
instances:      1/1
memory usage:   2048M
     state     since                  cpu    memory         disk           details
#0   running   2021-11-16T07:04:49Z   0.6%   284.8M of 2G   148.3M of 1G
```

Using Postman, I try to POST to this URL:

https://objectstore-sample-svc_4585-grateful-dog-on.cfapps.eu10.hana.ondemand.com/objectstorage.svc/api/v1/storage/
But the response is "HTTP Status 400 – Bad Request"

cf logs when post a file:
`2021-11-16T16:33:25.41+0900 [RTR/37] OUT *******.com - [2021-11-16T07:33:25.234238693Z] "POST /objectstorage.svc/api/v1/storage/ HTTP/1.1" 400 23772 435 "-" "PostmanRuntime/7.28.4" "-" "10.0.202.4:61025" x_forwarded_for:"-" x_forwarded_proto:"https" vcap_request_id:"3bb39507-5746-4175-72cb-4700949fd2a7" response_time:0.173022 gorouter_time:0.082832 app_id:"6aeecd61-714a-4a95-8699-a9dc27e7fd7e" app_index:"0" instance_id:"5254fd73-c646-4c0d-6f5b-8593" x_cf_routererror:"-" x_correlationid:"-" tenantid:"-" sap_passport:"-" x_scp_request_id:"264eea94-08f1-4542-9f3e-f675a6435370-61935E90-E77C24" x_cf_app_instance:"-" x_forwarded_host:"-" x_custom_host:"-" x_ssl_client:"-" x_ssl_client_session_id:"-" x_ssl_client_verify:"-" x_ssl_client_subject_dn:"-" x_ssl_client_subject_cn:"-" x_ssl_client_issuer_dn:"-" x_ssl_client_notbefore:"-" x_ssl_client_notafter:"-" x_b3_traceid:"424919723e7170b8" x_b3_spanid:"424919723e7170b8" x_b3_parentspanid:"-" b3:"424919723e7170b8-424919723e7170b8"`

Could you please tell me the cause?

Thanks.

**Comment by biswaranjanray** [comment]
Hi,

Sorry, we couldn't reproduce the issue. We're able to perform POST operation for all the supported cloud-providers. 
400 – Bad Request is normally thrown due to client side issues e.g incorrect URL.

I used your exact manifest.yml and deployed my application. One difference I noticed in the route, the app name is **objectstore-sample-svc_4585** but the route is found to be **objectstore-sample-svc4585**. The _ is removed. But in your case the route still contains the _. You may cross check your route and post the request again.

Also in POSTMAN before you send a POST request, make sure the **Body** is set to **form-data**, **Key** is set to **File**, enter **Key** name as **file** and in **Value** select a file.

Thanks

**Comment by kyoneo** [comment]
Hi,
Thanks for your reply and sorry for not contacting you, but I actually succeeded in changing app name and re-creating the project.

> One difference I noticed in the route, the app name is objectstore-sample-svc_4585 but the route is found to be objectstore-sample-svc4585. The _ is removed. But in your case the route still contains the _. You may cross check your route and post the request again.

As you pointed out, I solved the problem by using an app name that does not contain _.

I'm sorry to have taken up your time with such a trivial mistake, but I hope you'll let me ask you another question!

Thanks

**Comment by biswaranjanray** [comment]
Hi,

If you're able to resolve your issue with the solution offered above, may I request you to close the issue if you have no further questions.

Thanks

**Comment by kyoneo** [comment]
Hi,
I'm sorry for leaving this. I closed it.

Thanks

**Comment by biswaranjanray** [comment]
Thank you. Appreciate it.
