### ISSUE TITLE
Unable to Create File

### ISSUE THREAD

**Issue by eartherian** [SAP-samples/cloud-objectstore-java-sample#2]
Hi,

Was able to push the app to a space in CF successfully but while testing the url in POST mode to place a file - I am getting a response as [] with the Status 200.

![objectstore](https://user-images.githubusercontent.com/9512605/84047592-17245880-a9c9-11ea-8f06-125663674f4b.png)

Any comments or suggestions are welcome!

Thanks!

**Comment by biswaranjanray** [comment]
Hi,

Sorry for the late response. 

The response you should ideally get on a successful file upload is: "<file name> is successfully uploaded" with a status 202 created.  But the response you are getting as [] with status 200 is expected when a GET request is sent to the api endpoint "https://<your cf endpoint>.objectstorage.svc/api/v1/storage/" and if there are no files available in a particular container depending on which landscape your application is pushed into in cf e.g aws or gcp. 

![GET](https://user-images.githubusercontent.com/30648646/85741983-823b9200-b720-11ea-8f52-5d3f91938080.jpg)

Please check in the cf logs if you are getting this message "Upload started" and "upload completed" on submitting a POST request.
The application currently supports AWS and GCP with service plans "s3-standard" and "gcs-standard" respectively. 

Thanks.

**Comment by indusankar89** [comment]
Please reopen the issue if it still persists.
