### ISSUE TITLE
Will enhance it to support Alibaba Cloud OSS with Jcloud?

### ISSUE THREAD

**Issue by TIAXU** [SAP-samples/cloud-objectstore-java-sample#9]
SCP@Alicloud has landed for over one year, many customers have the requirement to use S3 API to access OSS with Jcloud. 

Although Jcloud doesn't support Ali OSS directly, users can still connect OSS with S3 API:
https://www.alibabacloud.com/help/doc-detail/64919.htm

I'm not sure if you will have the plan to do this?

Best regards,
Tia

**Comment by biswaranjanray** [comment]
Hi Tia,

I believe our colleagues have communicated you w.r.t the issue you raised. If your queries are addressed you may please close this issue. 
Please note AliCloud OSS is not yet officially supported by JClouds. The team is considering to support it through s3-compatible interface which is still open. Please have a look at the issue [JCLOUDS-1302](https://issues.apache.org/jira/browse/JCLOUDS-1302) to know more.

Thanks and Regards,
Biswa

**Comment by biswaranjanray** [comment]
Please let us know if we can close this issue.

**Comment by TIAXU** [comment]
Sure，please. Thanks for your support



发自我的iPhone


------------------ Original ------------------
From: Biswa Ranjan Ray ***@***.***&gt;
Date: Thu,Dec 30,2021 5:17 PM
To: SAP-samples/cloud-objectstore-java-sample ***@***.***&gt;
Cc: TIAXU ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [SAP-samples/cloud-objectstore-java-sample] Will enhance it to support Alibaba Cloud OSS with Jcloud? (#9)





 
Please let us know if we can close this issue.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by biswaranjanray** [comment]
Thank you.
